batch_size: 16
length: 64
epochs: 1001
steps_per_epoch: 128

print_frequency: 10
save_frequency: 10

samples_dir: './samples'
weights_dir: './checkpoints'

learning_rate: 0.0002
checkpoints: True

noDecom: False