batch_size: 32
length: 128
epochs: 601
steps_per_epoch: 128

print_frequency: 10
save_frequency: 10

samples_dir: './samples'
weights_dir: './checkpoints'

learning_rate: 0.00001
checkpoints: True

noDecom: False